apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: movie-manager-ingress
  annotations:
    kubernetes.io/ingress.class: "gce"
spec:
  ingressClassName: gce
  defaultBackend:
    service:
      name: movie-manager-frontend
      port:
        number: 80
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: movie-manager-backend
            port:
              number: 5000
